// Reference data sourced from the GTVET-IDMS M1 Graduate List tracer form.
// Programs are editable at runtime (add/delete); the app seeds them from this list on first run.

const DEFAULT_PROGRAMS = [
  "AGRICULTURAL MECHANIZATION TECHNOLOGY",
  "ARCHITECTURAL DRAFTING",
  "AUTOBODY WORKS",
  "BIODIGESTER CONSTRUCTION (CBT OPTION)",
  "BUILDING CONSTRUCTION TECHNOLOGY",
  "BUILDING CONSTRUCTION TECHNOLOGY (CBT OPTION)",
  "BUSINESS ACCOUNTING",
  "BUSINESS INFORMATION TECHNOLOGY",
  "BUSINESS SECRETARIAL",
  "BUSINESS SYSTEMS TECHNOLOGY",
  "COMPUTER HARDWARE TECHNOLOGY",
  "COMPUTER NETWORKING (CBT OPTION, FOR GIRLS ONLY)",
  "COSMETOLOGY",
  "CREATIVE ART TECHNOLOGY",
  "DATABASE MANAGEMENT (CBT OPTION, FOR GIRLS ONLY)",
  "DIESEL MECH/HEAVY ENGINE, HEAVY DUTY",
  "DIGITAL DESIGNING TECHNOLOGY",
  "ELECTRICAL ENGINEERING TECHNOLOGY",
  "ELECTRICAL MACHINE/MOTOR REWINDING",
  "ELECTRONICS ENGINEERING",
  "FASHION DESIGNING TECHNOLOGY",
  "FURNITURE DESIGN & CONSTRUCTION",
  "GENERAL TEXTILES",
  "HOSPITALITY & CATERING MANAGEMENT",
  "INDUSTRIAL MECHANICS",
  "INFORMATION TECHNOLOGY",
  "LEATHER WORKS",
  "MECHANICAL ENGINEERING TECHNOLOGY",
  "MOTOR VEHICLE ENGINEERING",
  "PLUMBING & GAS FITTING TECHNOLOGY",
  "PRINTING",
  "REFRIGERATION & AIR-CONDITION TECHNOLOGY",
  "SMALL ENGINE REPAIR",
  "SOFTWARE DEVELOPMENT (CBT OPTION, FOR GIRLS ONLY)",
  "SOLAR PHOTOVOLTAIC TECHNOLOGY",
  "UPHOLSTERY",
  "VISUAL COMMUNICATION TECHNOLOGY",
  "WELDING AND FABRICATION TECHNOLOGY",
  "WOOD CONSTRUCTION TECHNOLOGY",
  "ENGLISH LANGUAGE",
  "ENTREPRENEURSHIP SKILLS",
  "ICT",
  "INTEGRATED SCIENCE",
  "MATHEMATICS",
  "SOCIAL STUDIES"
];

const EXAM_TYPES = [
  "CERTIFICATE I - NVTI",
  "CERTIFICATE II - NVTI",
  "CERTIFICATE II - TEU",
  "CERTIFICATE II (CORE) - CTVET",
  "NATIONAL CERTIFICATE I - CTVET",
  "NATIONAL CERTIFICATE II - CTVET",
  "NATIONAL PROFICIENCY I - CTVET",
  "NATIONAL PROFICIENCY II - CTVET",
  "PROFICIENCY I - NVTI",
  "PROFICIENCY I - TEU",
  "PROFICIENCY II - NVTI",
  "PROFICIENCY II - TEU"
];

const REGIONS = [
  "Ahafo", "Ashanti", "Bono", "Bono East", "Central", "Eastern",
  "Greater Accra", "North East", "Northern", "Oti", "Savannah",
  "Upper East", "Upper West", "Volta", "Western", "Western North"
];

const IMPAIRMENT_TYPES = [
  "Attention Deficit Disorders",
  "Autism",
  "Cerebral Palsy",
  "Down Syndrome",
  "Hearing Impairment",
  "Intellectual Disabilities",
  "Mental Disability",
  "Physically Challenged",
  "Visual Impairment"
];

const HOUSE_COLORS = [
  "#C49B3A", "#8E3B3B", "#2F6F4E", "#3B5B8E", "#7A4B8E", "#B3672B"
];
